name: Auto Assign

# Triggers when issues or pull requests are opened
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  contents: write
  issues: write
  pull-requests: write
  repository_projects: write
  security_events: write
  statuses: write
  actions: write
  checks: write
  deployments: write
  discussions: write
  packages: write
  pages: write
  repository-projects: write
  security-events: write
  id-token: write

jobs:
  auto_assign_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      repository_projects: write
      security_events: write
      statuses: write
      actions: write
      checks: write
      deployments: write
      discussions: write
      packages: write
      pages: write
      repository-projects: write
      security-events: write
      id-token: write

    # Steps to be executed in this job
    steps:
      # Automatically assigns an issue to user rootgov
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: rootgov
          numOfAssignee: 1

      # Additional step with a valid GitHub action
      - name: 'Additional step'
        uses: ${{ github.action }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: rootgov
          numOfAssignee: 1
